import Testing
@testable import CmdV

struct PrivacyGateTests {
    @Test(arguments: [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.apple.is-remote-clipboard",
    ])
    func transientTypesAreSkipped(type: String) {
        let verdict = PrivacyGate.evaluate(
            isSelfCopy: false,
            types: ["public.utf8-plain-text", type],
            sourceAppBundleID: "com.apple.Safari",
            excludedApps: []
        )
        #expect(verdict == .skipTransientType(type))
    }

    @Test func selfCopyIsSkipped() {
        let verdict = PrivacyGate.evaluate(
            isSelfCopy: true,
            types: ["public.utf8-plain-text"],
            sourceAppBundleID: nil,
            excludedApps: []
        )
        #expect(verdict == .skipSelfCopy)
    }

    @Test func selfCopyWinsOverTransientType() {
        // Ordering: the self-copy check must run before the type check.
        let verdict = PrivacyGate.evaluate(
            isSelfCopy: true,
            types: ["org.nspasteboard.ConcealedType"],
            sourceAppBundleID: nil,
            excludedApps: []
        )
        #expect(verdict == .skipSelfCopy)
    }

    @Test func excludedAppIsSkipped() {
        let verdict = PrivacyGate.evaluate(
            isSelfCopy: false,
            types: ["public.utf8-plain-text"],
            sourceAppBundleID: "com.1password.1password",
            excludedApps: ["com.1password.1password"]
        )
        #expect(verdict == .skipExcludedApp("com.1password.1password"))
    }

    @Test func normalCopyIsRecorded() {
        let verdict = PrivacyGate.evaluate(
            isSelfCopy: false,
            types: ["public.utf8-plain-text", "public.rtf"],
            sourceAppBundleID: "com.apple.Safari",
            excludedApps: ["com.1password.1password"]
        )
        #expect(verdict == .record)
    }

    @Test func nilSourceAppWithExclusionsIsRecorded() {
        let verdict = PrivacyGate.evaluate(
            isSelfCopy: false,
            types: ["public.utf8-plain-text"],
            sourceAppBundleID: nil,
            excludedApps: ["com.1password.1password"]
        )
        #expect(verdict == .record)
    }
}
