import Foundation

/// Decides whether a pasteboard change may be recorded.
/// Pure logic — no AppKit — so it is fully unit-testable.
struct PrivacyGate {
    enum Verdict: Equatable {
        case record
        case skipSelfCopy
        case skipTransientType(String)
        case skipExcludedApp(String)
    }

    /// Pasteboard types that mark content as transient, concealed, or
    /// machine-generated. See https://nspasteboard.org.
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.apple.is-remote-clipboard",
    ]

    /// Ordered gate: self-copy first (cheapest, most common during pastes),
    /// then transient/concealed types, then per-app exclusions.
    static func evaluate(
        isSelfCopy: Bool,
        types: Set<String>,
        sourceAppBundleID: String?,
        excludedApps: Set<String>
    ) -> Verdict {
        if isSelfCopy {
            return .skipSelfCopy
        }
        if let match = types.first(where: { ignoredTypes.contains($0) }) {
            return .skipTransientType(match)
        }
        if let source = sourceAppBundleID, excludedApps.contains(source) {
            return .skipExcludedApp(source)
        }
        return .record
    }
}
